trigger:
  branches:
    include:
      - "*"

pool: Default

steps:
- task: Gradle@2
  inputs:
    versionOption: '5.x'
    maximumHeapSize: '2'
- script: ./gradlew assemble assembleTestEmptyLibXCFramework spmDevBuild
  displayName: 'Run Gradle tasks'
- script: |
    git clone https://ryan.foster:shd6hlvjaecubwvxeep2a3mwxj5idgb6em4cdqctktxynttipfkq@dev.azure.com/test-kmm-bridge-devops/Test%20KMM%20Pipe/_git/SPM%20Repo spm-repo
    cp -r build/spm-package/Package.swift spm-repo/
    cd spm-repo
    git config user.email "you@example.com"
    git config user.name "Your Name"
    git add -A
    git commit -m "Update Package.swift"
    git push
  displayName: 'Commit and push updated Package.swift to SPM Repo'
- script: |
    git tag "v$(date +'%Y.%m.%d.%H.%M.%S')"
    git push origin --tags
  displayName: 'Create new version tag in SPM Repo'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'shared/build/out/xcframework'
    artifactName: 'XCFramework'
    publishLocation: 'Container'
- script: |
    sudo apt-get install clang libicu-dev
    mkdir swift-install
    cd swift-install
    wget https://swift.org/builds/swift-5.2.4-release/ubuntu1804/swift-5.2.4-RELEASE/swift-5.2.4-RELEASE-ubuntu18.04.tar.gz
    tar -xvzf swift-5.2.4-RELEASE*
    export PATH=$PATH:$(pwd)/swift-5.2.4-RELEASE-ubuntu18.04
    swift -version
  displayName: "Install Swift"