trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: 'macOS-latest'

steps:
- task: UseGradle@0
  inputs:
    versionOption: '5.x'
    maximumHeapSize: '2'
- script: ./gradlew assemblePublixAnalyticsSdkXCFramework
  displayName: 'Run Gradle task'
- script: |
    git config user.email "you@example.com"
    git config user.name "Your Name"
    git add -A
    git commit -m "Update XCFramework"
  displayName: 'Commit updated XCFramework'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'shared/build/out/xcframework'
    artifactName: 'XCFramework'
    publishLocation: 'Container'
- script: |
    sudo apt-get install clang libicu-dev
    mkdir swift-install
    cd swift-install
    wget https://swift.org/builds/swift-5.2.4-release/ubuntu1804/swift-5.2.4-RELEASE/swift-5.2.4-RELEASE-ubuntu18.04.tar.gz
    tar -xvzf swift-5.2.4-RELEASE*
    export PATH=$PATH:$(pwd)/swift-5.2.4-RELEASE-ubuntu18.04
    swift -version
  displayName: "Install Swift"
- script: |
    swift test
  displayName: "Run unit tests"
