trigger:
  branches:
    include:
      - "*"

pool: 
  vmImage: 'macOs-latest'

steps:
- checkout: self
  fetchDepth: 0
- script: git checkout master


- script: |
    echo API_KEY=$(API_KEY) >> secure.properties
    echo JWT_TOKEN=$(JWT_TOKEN) >> secure.properties
    echo CLIENT_SECRET=$(CLIENT_SECRET) >> secure.properties
    echo DATA_STREAM_ID=$(DATA_STREAM_ID) >> secure.properties
    echo IMS=$(IMS) >> secure.properties
  displayName: 'Generate secure.properties'
- task: Gradle@2
  inputs:
   gradleWrapperFile: 'gradlew'
   jdkVersionOption: '1.17'
- script: |
    ./gradlew -PENABLE_PUBLISHING=true publishPublixAnalytics-androidPublicationToMavenRepository
    ./gradlew -PENABLE_PUBLISHING=true kmmBridgePublish
  displayName: 'Publish android and ios libraries'
